name: Toucanet SDK

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  test:
    timeout-minutes: 5
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: pub get

      - name: Format
        run: dartfmt --dry-run --set-exit-if-changed .

      - name: Analyze
        run: dartanalyzer --fatal-infos --fatal-warnings lib test

      - name: Run tests
        run: dart test --coverage=coverage && pub run coverage:format_coverage --lcov --in=coverage --out=coverage/lcov.info --packages=.packages --report-on=lib

      - name: Check coverage
        uses: VGVentures/very-good-coverage@v1.1.0
        with:
          path: "./coverage/lcov.info"
          min_coverage: 100
